apiVersion: v1
kind: Service
metadata:
  labels:
    app: slackernews
  name: slackernews
spec:
  ports:
  - name: http
    port: 3000
    targetPort: http
  selector:
    app: slackernews
  type: ClusterIP
